(eval-when (:compile-toplevel :execute :load-toplevel)
  (ql:quickload "cl-rust-generator"))

(in-package :cl-rust-generator)

;; gen00_proto.lisp — generates the shared UART frame protocol crate.
;;
;; Wire format (all multi-byte integers little-endian):
;;   [MAGIC=0xAA] [LEN: u8, 1..=64] [PAYLOAD: LEN bytes] [CRC16-CCITT lo] [CRC16-CCITT hi]
;; CRC covers LEN + PAYLOAD.
;; First payload byte is the message tag (host->fw 0x01..0x05, fw->host 0x10..0x12).
;; no_std compatible (uses core only). Unit tests run on the host.

(let ((*omit-redundant-parens* t))
  (defparameter *source-dir* #P"examples/23_embassy_pico/proto/src/")
  (defparameter *code-file* (asdf:system-relative-pathname 'cl-rust-generator (merge-pathnames #P"lib.rs"
											       *source-dir*)))
  (ensure-directories-exist *code-file*)
  (write-source
   *code-file*
   `(do0
     "#![cfg_attr(not(test), no_std)]"
     "//! pico-link: framed UART protocol shared by Pico 2 firmware and Linux host."
     "//! Frame: [0xAA][LEN][PAYLOAD..][CRC lo][CRC hi], CRC16-CCITT over LEN+PAYLOAD."

     "pub const FRAME_MAGIC: u8 = 0xAA;"
     "pub const MAX_PAYLOAD: usize = 64;"
     "pub const FRAME_OVERHEAD: usize = 4;"
     "pub const TAG_SET_PWM: u8 = 1;"
     "pub const TAG_SET_HSTX: u8 = 2;"
     "pub const TAG_SET_ADC: u8 = 3;"
     "pub const TAG_CAP_SELECT: u8 = 4;"
     "pub const TAG_READ_BLOCK: u8 = 5;"
     "pub const TAG_STATUS: u8 = 16;"
     "pub const TAG_ADC_BLOCK: u8 = 17;"
     "pub const TAG_ACK: u8 = 18;"

     (space pub (defun crc16_part (data start len)
       (declare (type "&[u8]" data)
		(type usize start len)
		(values u16))
       (let ((crc (hex 65535))
	     (i 0))
	 (declare (type u16 crc)
		  (type usize i)
		  (mutable crc i))
	 (while (< i len)
	   (setf crc (logxor crc (* (coerce (aref data (+ start i)) u16) 256)))
	   (dotimes (_ 8)
	     (if (!= (logand crc (hex 32768)) 0)
		 (setf crc (logxor (<< crc 1) (hex 4129)))
	       (setf crc (<< crc 1))))
	   (incf i))
	 crc)))

     (space pub (defun crc16_ccitt (data)
       (declare (type "&[u8]" data)
		(values u16))
       (crc16_part data 0 (dot data (len)))))

     (space pub (defun encode_frame (payload out)
       (declare (type "&[u8]" payload)
		(type "&mut [u8]" out)
		(values "Option<usize>"))
       (let ((n (dot payload (len))))
	 (declare (type usize n))
	 (when (or (== n 0) (< MAX_PAYLOAD n))
	   (return None))
	 (let ((total (+ n FRAME_OVERHEAD)))
	   (declare (type usize total))
	   (when (< (dot out (len)) total)
	     (return None))
	   (setf (aref out 0) FRAME_MAGIC)
	   (setf (aref out 1) (coerce n u8))
	   (let ((i 0))
	     (declare (type usize i)
		      (mutable i))
	     (while (< i n)
	       (setf (aref out (+ i 2)) (aref payload i))
	       (incf i)))
	   (let ((crc (crc16_part out 1 (+ n 1))))
	     (declare (type u16 crc))
	     (setf (aref out (+ n 2)) (coerce (logand crc (hex ff)) u8))
	     (setf (aref out (+ n 3)) (coerce (>> crc 8) u8)))
	   (return (Some total))))))

     (space pub (defun put_u16_le (o i v)
       (declare (type "&mut [u8]" o)
		(type usize i)
		(type u16 v))
       (setf (aref o i) (coerce (logand v (hex ff)) u8))
       (setf (aref o (+ i 1)) (coerce (>> v 8) u8))))
     (space pub (defun get_u16_le (d i)
       (declare (type "&[u8]" d)
		(type usize i)
		(values u16))
       (logior (coerce (aref d i) u16)
	       (* (coerce (aref d (+ i 1)) u16) 256))))
     (space pub (defun put_u32_le (o i v)
       (declare (type "&mut [u8]" o)
		(type usize i)
		(type u32 v))
       (setf (aref o i) (coerce (logand v (hex ff)) u8))
       (setf (aref o (+ i 1)) (coerce (logand (>> v 8) (hex ff)) u8))
       (setf (aref o (+ i 2)) (coerce (logand (>> v 16) (hex ff)) u8))
       (setf (aref o (+ i 3)) (coerce (>> v 24) u8))))
     (space pub (defun get_u32_le (d i)
       (declare (type "&[u8]" d)
		(type usize i)
		(values u32))
       (logior (logior (coerce (aref d i) u32)
		       (* (coerce (aref d (+ i 1)) u32) 256))
	       (logior (* (coerce (aref d (+ i 2)) u32) 65536)
		       (* (coerce (aref d (+ i 3)) u32) 16777216)))))

     (space pub (defstruct0 Decoder
       (buf "[u8; 70]")
       (pos usize)
       (frame_len usize)
       (errors u32)))

     (impl Decoder
	   (space pub (defun new ()
	     (declare (values Decoder))
	     (make-instance Decoder :buf (array-repeat 0 70) :pos 0 :frame_len 0 :errors 0)))
	   (space pub (defun reset ("&mut self")
	     (setf (dot self pos) 0)
	     (setf (dot self frame_len) 0)))
	   (space pub (defun error_count ("&self")
	     (declare (values u32))
	     (dot self errors)))
	   (space pub (defun payload_len ("&self")
	     (declare (values usize))
	     (dot self frame_len)))
	   (space pub (defun payload_byte ("&self" i)
	     (declare (type usize i)
		      (values u8))
	     (aref (dot self buf) i)))
	   (space pub (defun push ("&mut self" byte)
	     (declare (type u8 byte)
		      (values "Option<usize>"))
	     (when (== (dot self pos) 0)
	       (when (!= byte FRAME_MAGIC)
		 (incf (dot self errors))
		 (return None))
	       (setf (aref (dot self buf) 0) byte)
	       (setf (dot self pos) 1)
	       (return None))
	     (setf (aref (dot self buf) (dot self pos)) byte)
	     (incf (dot self pos))
	     (when (== (dot self pos) 2)
	       (let ((n (coerce (aref (dot self buf) 1) usize)))
		 (declare (type usize n))
		 (when (or (== n 0) (< MAX_PAYLOAD n))
		   (setf (dot self pos) 0)
		   (incf (dot self errors))
		   (return None))))
	     (let ((n (coerce (aref (dot self buf) 1) usize)))
	       (declare (type usize n))
	       (when (< (dot self pos) (+ n FRAME_OVERHEAD))
		 (return None))
	       (let ((crc (crc16_part (ref (dot self buf)) 1 (+ n 1)))
		     (got (logior (coerce (aref (dot self buf) (+ n 2)) u16)
				  (* (coerce (aref (dot self buf) (+ n 3)) u16) 256))))
		 (declare (type u16 crc got))
		 (when (!= crc got)
		   (setf (dot self pos) 0)
		   (incf (dot self errors))
		   (return None))
		 (let ((i 0))
		   (declare (type usize i)
			    (mutable i))
		   (while (< i n)
		     (setf (aref (dot self buf) i) (aref (dot self buf) (+ i 2)))
		     (incf i)))
		 (setf (dot self frame_len) n)
		 (setf (dot self pos) 0)
		 (return (Some n)))))))

     (space pub (defstruct0 PwmCmd ((space pub ch) u8) ((space pub freq_hz) u32) ((space pub amp_tenth_pct) u16) ((space pub phase_deg) u16)))
     (space pub (defun encode_pwm_cmd (cmd out)
       (declare (type "&PwmCmd" cmd)
		(type "&mut [u8; 10]" out))
       (setf (aref out 0) TAG_SET_PWM)
       (setf (aref out 1) (dot cmd ch))
       (put_u32_le out 2 (dot cmd freq_hz))
       (put_u16_le out 6 (dot cmd amp_tenth_pct))
       (put_u16_le out 8 (dot cmd phase_deg))))
     (space pub (defun decode_pwm_cmd (p)
       (declare (type "&[u8]" p)
		(values "Option<PwmCmd>"))
       (when (or (!= (dot p (len)) 10) (!= (aref p 0) TAG_SET_PWM))
	 (return None))
       (return (Some (make-instance PwmCmd
				    :ch (aref p 1)
				    :freq_hz (get_u32_le p 2)
				    :amp_tenth_pct (get_u16_le p 6)
				    :phase_deg (get_u16_le p 8))))))

     (space pub (defstruct0 HstxCmd ((space pub freq_hz) u32) ((space pub amp_tenth_pct) u16) ((space pub phase_deg) u16)))
     (space pub (defun encode_hstx_cmd (cmd out)
       (declare (type "&HstxCmd" cmd)
		(type "&mut [u8; 9]" out))
       (setf (aref out 0) TAG_SET_HSTX)
       (put_u32_le out 1 (dot cmd freq_hz))
       (put_u16_le out 5 (dot cmd amp_tenth_pct))
       (put_u16_le out 7 (dot cmd phase_deg))))
     (space pub (defun decode_hstx_cmd (p)
       (declare (type "&[u8]" p)
		(values "Option<HstxCmd>"))
       (when (or (!= (dot p (len)) 9) (!= (aref p 0) TAG_SET_HSTX))
	 (return None))
       (return (Some (make-instance HstxCmd
				    :freq_hz (get_u32_le p 1)
				    :amp_tenth_pct (get_u16_le p 5)
				    :phase_deg (get_u16_le p 7))))))

     (space pub (defstruct0 AdcCmd ((space pub rate_hz) u32) ((space pub phase_deg) u16)))
     (space pub (defun encode_adc_cmd (cmd out)
       (declare (type "&AdcCmd" cmd)
		(type "&mut [u8; 7]" out))
       (setf (aref out 0) TAG_SET_ADC)
       (put_u32_le out 1 (dot cmd rate_hz))
       (put_u16_le out 5 (dot cmd phase_deg))))
     (space pub (defun decode_adc_cmd (p)
       (declare (type "&[u8]" p)
		(values "Option<AdcCmd>"))
       (when (or (!= (dot p (len)) 7) (!= (aref p 0) TAG_SET_ADC))
	 (return None))
       (return (Some (make-instance AdcCmd
				    :rate_hz (get_u32_le p 1)
				    :phase_deg (get_u16_le p 5))))))

     (space pub (defstruct0 StatusMsg ((space pub seq) u8) ((space pub temp_c10) i16) ((space pub cap) u32) ((space pub flags) u8)))
     (space pub (defun encode_status (msg out)
       (declare (type "&StatusMsg" msg)
		(type "&mut [u8; 9]" out))
       (setf (aref out 0) TAG_STATUS)
       (setf (aref out 1) (dot msg seq))
       (put_u16_le out 2 (coerce (dot msg temp_c10) u16))
       (put_u32_le out 4 (dot msg cap))
       (setf (aref out 8) (dot msg flags))))
     (space pub (defun decode_status (p)
       (declare (type "&[u8]" p)
		(values "Option<StatusMsg>"))
       (when (or (!= (dot p (len)) 9) (!= (aref p 0) TAG_STATUS))
	 (return None))
       (return (Some (make-instance StatusMsg
				    :seq (aref p 1)
				    :temp_c10 (coerce (get_u16_le p 2) i16)
				    :cap (get_u32_le p 4)
				    :flags (aref p 8))))))

     (space pub (defun block_sample (p i)
       (declare (type "&[u8]" p)
		(type usize i)
		(values u16))
       (get_u16_le p (+ 3 (* i 2)))))

     "#[cfg(test)]"
     "mod tests {"
     "use super::*;"
     "#[test]"
     (defun crc_known_vector ()
       (let ((v (string-b "123456789")))
	 (assert_eq! (hex 10673) (crc16_ccitt v))))
     "#[test]"
     (defun frame_round_trip ()
       (let ((payload (list 1 2 3))
	     (out (array-repeat 0 16)))
	 (declare (type "[u8; 3]" payload)
		  (type "[u8; 16]" out)
		  (mutable out))
	 (let-else ((Some n) (encode_frame (ref payload) "&mut out"))
	   (return))
	 (assert_eq! n 7)
	 (let ((dec (Decoder--new))
	       (got None))
	   (declare (type "Option<usize>" got)
		    (mutable dec got))
	   (dotimes (i n)
	     (setf got (dec.push (aref out i))))
	   (let-else ((Some m) got)
	     (return))
	   (assert_eq! m 3)
	   (assert_eq! 1 (dec.payload_byte 0))
	   (assert_eq! 3 (dec.payload_byte 2)))))
     "#[test]"
     (defun frame_rejects_bad_crc ()
       (let ((payload (list 9 9))
	     (out (array-repeat 0 16)))
	 (declare (type "[u8; 2]" payload)
		  (type "[u8; 16]" out)
		  (mutable out))
	 (let-else ((Some n) (encode_frame (ref payload) "&mut out"))
	   (return))
	 (setf (aref out 3) (logxor (aref out 3) (hex ff)))
	 (let ((dec (Decoder--new)))
	   (declare (mutable dec))
	   (dotimes (i n)
	     (let ((_ (dec.push (aref out i))))))
	   (assert_eq! 1 (dec.error_count)))))
     "#[test]"
     (defun frame_rejects_garbage ()
       (let ((dec (Decoder--new)))
	 (declare (mutable dec))
	 (dec.push 0)
	 (dec.push 1)
	 (assert_eq! 2 (dec.error_count))))
     "#[test]"
     (defun frame_rejects_empty_and_oversize ()
       (let ((empty (array-repeat 0 0))
	     (out (array-repeat 0 80)))
	 (declare (type "[u8; 0]" empty)
		  (type "[u8; 80]" out)
		  (mutable out))
	 (case (encode_frame (ref empty) "&mut out")
	   ((Some _) (return))
	   (None nil))
	 (let ((big (array-repeat 7 65)))
	   (declare (type "[u8; 65]" big))
	   (case (encode_frame (ref big) "&mut out")
	     ((Some _) (return))
	     (None nil)))))
     "#[test]"
     (defun pwm_cmd_round_trip ()
       (let ((cmd (make-instance PwmCmd :ch 3 :freq_hz 440 :amp_tenth_pct 800 :phase_deg 90))
	     (wire (array-repeat 0 10)))
	 (declare (type "[u8; 10]" wire)
		  (mutable wire))
	 (encode_pwm_cmd (ref cmd) "&mut wire")
	 (let-else ((Some back) (decode_pwm_cmd (ref wire)))
	   (return))
	 (assert_eq! 3 (dot back ch))
	 (assert_eq! 440 (dot back freq_hz))
	 (assert_eq! 800 (dot back amp_tenth_pct))
	 (assert_eq! 90 (dot back phase_deg))))
     "#[test]"
     (defun status_negative_temp ()
       (let ((msg (make-instance StatusMsg :seq 7 :temp_c10 -55 :cap 123456 :flags 1))
	     (wire (array-repeat 0 9)))
	 (declare (type "[u8; 9]" wire)
		  (mutable wire))
	 (encode_status (ref msg) "&mut wire")
	 (let-else ((Some back) (decode_status (ref wire)))
	   (return))
	 (assert_eq! 7 (dot back seq))
	 (assert_eq! -55 (dot back temp_c10))
	 (assert_eq! 123456 (dot back cap))))
     "}")))
