(eval-when (:compile-toplevel :execute :load-toplevel)
  (ql:quickload "cl-rust-generator"))

(in-package :cl-rust-generator)

;; gen10_firmware.lisp — generates the Pico 2 Embassy firmware (fw_pico2).
;; Peripherals: UART0 (proto frames) / ADC 26-28+temp / PWM slices 1-4 (sine
;; via duty) / PIO0 cap sensing on PIN_22 + Flex on 20,21,23 / HSTX lane 0
;; via PAC + DMA ring. Host sends param commands, firmware streams status.

(let ((*omit-redundant-parens* t))
  (defparameter *source-dir* #P"examples/23_embassy_pico/fw_pico2/src/")
  (defparameter *code-file* (asdf:system-relative-pathname 'cl-rust-generator (merge-pathnames #P"main.rs"
											       *source-dir*)))
  (ensure-directories-exist *code-file*)
  (write-source
   *code-file*
   `(do0
     "#![no_std]"
     "#![no_main]"
     "use defmt_rtt as _;"
     "use embassy_rp::adc::{Adc, Channel as AdcChannel, Config as AdcConfig};"
     "use embassy_rp::gpio::{Flex, Level, Output, Pull};"
     "use embassy_rp::pio::{Config as PioConfig, Pio};"
     "use embassy_rp::pwm::{Config as PwmConfig, Pwm};"
     "use embassy_rp::uart::{Config as UartConfig, Uart};"
     "use embassy_rp::{bind_interrupts, pac};"
     "use embassy_time::{Duration, Instant, Ticker, Timer};"
     "use embedded_io_async::{Read, Write};"
     "use panic_probe as _;"
     "use pico_link_proto as proto;"
     "use pio::pio_asm;"
     "embassy_rp::bind_interrupts!(struct Irqs {"
     "    ADC_IRQ_FIFO => embassy_rp::adc::InterruptHandler;"
     "    PIO0_IRQ_0 => embassy_rp::pio::InterruptHandler<embassy_rp::peripherals::PIO0>;"
     "    UART0_IRQ => embassy_rp::uart::BufferedInterruptHandler<embassy_rp::peripherals::UART0>;"
     "});"
     "static PWM_CH: embassy_sync::channel::Channel<embassy_sync::blocking_mutex::raw::ThreadModeRawMutex, pico_link_proto::PwmCmd, 8> = embassy_sync::channel::Channel::new();"
     "static HSTX_CH: embassy_sync::channel::Channel<embassy_sync::blocking_mutex::raw::ThreadModeRawMutex, pico_link_proto::HstxCmd, 4> = embassy_sync::channel::Channel::new();"
     "static ADC_CH: embassy_sync::channel::Channel<embassy_sync::blocking_mutex::raw::ThreadModeRawMutex, pico_link_proto::AdcCmd, 4> = embassy_sync::channel::Channel::new();"
     "static CAP_CH: embassy_sync::channel::Channel<embassy_sync::blocking_mutex::raw::ThreadModeRawMutex, u8, 4> = embassy_sync::channel::Channel::new();"
     "static READ_CH: embassy_sync::channel::Channel<embassy_sync::blocking_mutex::raw::ThreadModeRawMutex, (u8, u16), 4> = embassy_sync::channel::Channel::new();"
     "static BLOCK_READY: embassy_sync::channel::Channel<embassy_sync::blocking_mutex::raw::ThreadModeRawMutex, (u8, u16), 2> = embassy_sync::channel::Channel::new();"
     "static BLOCK_BUF: embassy_sync::mutex::Mutex<embassy_sync::blocking_mutex::raw::ThreadModeRawMutex, [u16; 256]> = embassy_sync::mutex::Mutex::new([0; 256]);"
     "static BLOCK_META: embassy_sync::mutex::Mutex<embassy_sync::blocking_mutex::raw::ThreadModeRawMutex, (u8, u16)> = embassy_sync::mutex::Mutex::new((0, 0));"
     "static TEMP_VAL: embassy_sync::mutex::Mutex<embassy_sync::blocking_mutex::raw::ThreadModeRawMutex, u16> = embassy_sync::mutex::Mutex::new(0);"
     "static CAP_VAL: embassy_sync::mutex::Mutex<embassy_sync::blocking_mutex::raw::ThreadModeRawMutex, u32> = embassy_sync::mutex::Mutex::new(0);"
     "static CAP_PIO_VAL: embassy_sync::mutex::Mutex<embassy_sync::blocking_mutex::raw::ThreadModeRawMutex, u32> = embassy_sync::mutex::Mutex::new(0);"
     "static HSTX_BUF_CELL: static_cell::StaticCell<[u32; 256]> = static_cell::StaticCell::new();"
     "static UART_TX_BUF: static_cell::StaticCell<[u8; 256]> = static_cell::StaticCell::new();"
     "static UART_RX_BUF: static_cell::StaticCell<[u8; 256]> = static_cell::StaticCell::new();"
     "const SIN_Q16: [u16; 64] = [32768,35979,39160,42279,45307,48214,50972,53555,55938,58097,60013,61666,63041,64124,64905,65377,65535,65377,64905,64124,63041,61666,60013,58097,55938,53555,50972,48214,45307,42279,39160,35979,32768,29556,26375,23256,20228,17321,14563,11980,9597,7438,5522,3869,2494,1411,630,158,0,158,630,1411,2494,3869,5522,7438,9597,11980,14563,17321,20228,23256,26375,29556];"
     "const CAP_PROG: pio::Program<12> = pio_asm!("
     "    \"set pindirs, 1\","
     "    \"set pins, 1 [31]\","
     "    \"set pindirs, 0\","
     "    \"mov x, ~null\","
     "    \"again:\","
     "    \"jmp x--, dec\","
     "    \"mov isr, null\","
     "    \"push\","
     "    \"jmp again\","
     "    \"dec:\","
     "    \"jmp pin, again\","
     "    \"mov isr, x\","
     "    \"push\","
     "    \"jmp again\","
     ");"

     (defun temp_raw_to_c10 (raw)
       (declare (type u16 raw)
		(values i16))
       (let ((mv (/ (* (coerce raw i32) 3300) 4096)))
	 (declare (type i32 mv))
	 (coerce (- 270 (/ (* (- mv 706) 1000) 1721)) i16)))

     (defun pwm_carrier ()
       (declare (values PwmConfig))
       (let ((c (PwmConfig--default)))
	 (setf (dot c top) 6250)
	 c))

     (defun sine_step (freq_hz)
       (declare (type u32 freq_hz)
		(values u32))
       (coerce (/ (* (coerce freq_hz u64) 4294967296) 500) u32))

     (defun sine_duty (acc amp_tenth phase_off)
       (declare (type u32 acc)
		(type u16 amp_tenth)
		(type u32 phase_off)
		(values u16))
       (let ((idx (coerce (logand (+ (>> acc 26) phase_off) 63) usize)))
	 (declare (type usize idx))
	 (coerce (/ (* (/ (* (coerce (aref SIN_Q16 idx) u32) 6251) 65536) (coerce amp_tenth u32)) 1000) u16)))

     "#[embassy_executor::task]"
     (defun-async adc_task (adc pin0 pin1 pin2 pin_ts)
       (declare (type "embassy_rp::adc::Adc<'static, embassy_rp::adc::Async>" adc)
		(type "embassy_rp::peripherals::PIN_26" pin0)
		(type "embassy_rp::peripherals::PIN_27" pin1)
		(type "embassy_rp::peripherals::PIN_28" pin2)
		(type "embassy_rp::peripherals::ADC_TEMP_SENSOR" pin_ts)
		(mutable adc))
       (let ((c0 (embassy_rp--adc--Channel--new_pin pin0 Pull--None))
	     (c1 (embassy_rp--adc--Channel--new_pin pin1 Pull--None))
	     (c2 (embassy_rp--adc--Channel--new_pin pin2 Pull--None))
	     (cts (embassy_rp--adc--Channel--new_temp_sensor pin_ts))
	     (rate_hz 1000)
	     (temp_every 100)
	     (tick (Ticker--every (Duration--from_millis 1)))
	     (n 0)
	     (idx0 0)
	     (idx1 0)
	     (idx2 0)
	     (valid0 0)
	     (valid1 0)
	     (valid2 0)
	     (cap0 (array-repeat 0 256))
	     (cap1 (array-repeat 0 256))
	     (cap2 (array-repeat 0 256)))
	 (declare (type u32 rate_hz n temp_every)
		  (type usize idx0 idx1 idx2)
		  (type u16 valid0 valid1 valid2)
		  (type "[u16; 256]" cap0 cap1 cap2)
		  (mutable c0 c1 c2 cts tick n temp_every idx0 idx1 idx2 valid0 valid1 valid2 cap0 cap1 cap2))
	 (loop
	   (while-let ((Ok cmd) (dot ADC_CH (try_receive))
	     (setf rate_hz (dot (dot cmd rate_hz) (clamp 1 20000)))
	     (setf temp_every (if (< (/ rate_hz 10) 1) 1 (/ rate_hz 10)))
	     (setf tick (Ticker--every (Duration--from_micros (coerce (/ 1000000 rate_hz) u64))))
	     (await (Timer--after (Duration--from_micros (/ (* (coerce (dot cmd phase_deg) u64) 1000000) (* 360 (coerce rate_hz u64))))))))
	   (await (dot tick (next)))
	   (if-let ((Ok v) (await (dot adc (read "&mut c0")))
	     (do0 (setf (aref cap0 idx0) v)
		  (setf idx0 (% (+ idx0 1) 256))
		  (when (< valid0 256) (incf valid0)))))
	   (if-let ((Ok v) (await (dot adc (read "&mut c1")))
	     (do0 (setf (aref cap1 idx1) v)
		  (setf idx1 (% (+ idx1 1) 256))
		  (when (< valid1 256) (incf valid1)))))
	   (if-let ((Ok v) (await (dot adc (read "&mut c2")))
	     (do0 (setf (aref cap2 idx2) v)
		  (setf idx2 (% (+ idx2 1) 256))
		  (when (< valid2 256) (incf valid2)))))
	   (incf n)
	   (when (<= temp_every n)
	     (setf n 0)
	     (if-let ((Ok t) (await (dot adc (read "&mut cts")))
	       (do0 (let ((g (await (dot TEMP_VAL (lock)))))
		      (declare (mutable g))
		      (setf (deref g) t))))))
	   (while-let ((Ok req) (dot READ_CH (try_receive))
	     (let ((ch (dot req 0))
		   (want (dot req 1))
		   (m 0))
	       (declare (type u8 ch)
			(type u16 want m)
			(mutable m))
	       (if (== ch 0) (setf m (if (< want valid0) want valid0))
		   (if (== ch 1) (setf m (if (< want valid1) want valid1))
		       (setf m (if (< want valid2) want valid2))))
	       (let ((g (await (dot BLOCK_BUF (lock))))
		     (meta (await (dot BLOCK_META (lock)))))
		 (declare (mutable g meta))
		 (setf (dot meta 0) ch)
		 (setf (dot meta 1) m)
		 (let ((mu (coerce m usize)))
		 (declare (type usize mu))
		 (dotimes (j mu)
		   (if (== ch 0) (setf (aref g j) (aref cap0 (% (- (+ idx0 256) (- mu j)) 256)))
		       (if (== ch 1) (setf (aref g j) (aref cap1 (% (- (+ idx1 256) (- mu j)) 256)))
			   (setf (aref g j) (aref cap2 (% (- (+ idx2 256) (- mu j)) 256)))))))
	       (await (dot BLOCK_READY (send (paren ch m)))))))))))

     "#[embassy_executor::task]"
     (defun-async pwm_task (p0 p1 p2 p3)
       (declare (type "embassy_rp::pwm::Pwm<'static>" p0 p1 p2 p3))
       (let ((pwms (list p0 p1 p2 p3))
	     (freq (array-repeat 5 4))
	     (amp (array-repeat 800 4))
	     (ph (array-repeat 0 4))
	     (acc (array-repeat 0 4))
	     (tick (Ticker--every (Duration--from_millis 2))))
	 (declare (type "[u32; 4]" freq acc)
		  (type "[u16; 4]" amp ph)
		  (mutable pwms freq amp ph acc tick))
	 (loop
	   (while-let ((Ok cmd) (dot PWM_CH (try_receive))
	     (let ((ch (coerce (dot cmd ch) usize)))
	       (declare (type usize ch))
	       (when (< ch 4)
		 (setf (aref freq ch) (dot (dot cmd freq_hz) (clamp 1 1000)))
		 (setf (aref amp ch) (dot (dot cmd amp_tenth_pct) (clamp 0 1000)))
		 (setf (aref ph ch) (% (dot cmd phase_deg) 360))))))
	   (await (dot tick (next)))
	   (dotimes (ch 4)
	     (setf (aref acc ch) (+ (aref acc ch) (sine_step (aref freq ch))))
	     (let ((duty (sine_duty (aref acc ch) (aref amp ch) (/ (* (coerce (aref ph ch) u32) 64) 360)))
		   (cfg (pwm_carrier)))
	       (declare (mutable cfg))
	       (setf (dot cfg compare_a) duty)
	       (dot (aref pwms ch) (set_config "&cfg")))))))

     (defun flex_measure (f)
       (declare (type "&mut embassy_rp::gpio::Flex<'static>" f)
		(values u32))
       (dot f (set_as_output))
       (dot f (set_high))
       (dotimes (_ 6000)
	 (core--hint--spin_loop))
       (dot f (set_as_input))
       (let ((t0 (Instant--now))
	     (tries 0))
	 (declare (type u32 tries)
		  (mutable tries))
	 (while (and (dot f (is_high)) (< tries 200000))
	   (incf tries))
	 (coerce (dot (dot t0 (elapsed)) (as_micros)) u32)))

     "#[embassy_executor::task]"
     (defun-async cap_task (rx p20 p21 p23)
       (declare (type "embassy_rp::pio::StateMachineRx<'static, embassy_rp::peripherals::PIO0, 0>" rx)
		(type "embassy_rp::peripherals::PIN_20" p20)
		(type "embassy_rp::peripherals::PIN_21" p21)
		(type "embassy_rp::peripherals::PIN_23" p23)
		(mutable rx))
       (let ((flexes (list (Flex--new p20) (Flex--new p21) (Flex--new p23)))
	     (sel 3))
	 (declare (type "[embassy_rp::gpio::Flex<'static>; 3]" flexes)
		  (type u8 sel)
		  (mutable flexes sel))
	 (loop
	   (while-let ((Ok s) (dot CAP_CH (try_receive))
	     (setf sel (if (< s 4) s 3))))
	   (if (< sel 3)
	       (do0 (let ((v (flex_measure (ref-mut (aref flexes (coerce sel usize))))))
		      (declare (type u32 v))
		      (let ((g (await (dot CAP_VAL (lock)))))
			(declare (mutable g))
			(setf (deref g) v))))
	       (do0 (let ((g (await (dot CAP_PIO_VAL (lock)))))
		      (declare (mutable g))
		      (let ((h (await (dot CAP_VAL (lock)))))
			(declare (mutable h))
			(setf (deref h) (deref g))))))
	   (if-let ((Some v) (dot rx (try_pull))
	     (do0 (let ((g (await (dot CAP_PIO_VAL (lock)))))
		    (declare (mutable g))
		    (setf (deref g) v)))))
	   (await (Timer--after (Duration--from_millis 20))))))

     (defun hstx_init ()
       (dot (dot pac--RESETS (reset)) (modify (lambda (w) (dot w (set_hstx false)))))
       (dot (dot pac--RESETS (reset)) (modify (lambda (w) (dot w (set_dma false)))))
       (while (not (dot (dot pac--RESETS (reset_done)) (read) (hstx)))
	 (core--hint--spin_loop))
       (while (not (dot (dot pac--RESETS (reset_done)) (read) (dma)))
	 (core--hint--spin_loop))
       (dot (dot pac--CLOCKS (clk_hstx_ctrl)) (modify (lambda (w) (dot w (set_auxsrc pac--clocks--vals--ClkHstxCtrlAuxsrc--CLK_SYS)))))
       (dot (dot pac--CLOCKS (clk_hstx_ctrl)) (modify (lambda (w) (dot w (set_enable true)))))
       (dot (dot (dot pac--IO_BANK0 (gpio 12)) (ctrl)) (modify (lambda (w) (dot w (set_funcsel 0)))))
       (dot (dot pac--PADS_BANK0 (gpio 12)) (modify (lambda (w) (dot w (set_ie false)))))
       (dot (dot pac--PADS_BANK0 (gpio 12)) (modify (lambda (w) (dot w (set_od false)))))
       (dot (dot (dot pac--HSTX_CTRL (csr))) (modify (lambda (w) (dot w (set_en false)))))
       (dot (dot (dot pac--HSTX_CTRL (csr))) (modify (lambda (w) (dot w (set_expand_en false)))))
       (dot (dot (dot pac--HSTX_CTRL (csr))) (modify (lambda (w) (dot w (set_shift 31)))))
       (dot (dot (dot pac--HSTX_CTRL (csr))) (modify (lambda (w) (dot w (set_n_shifts 0)))))
       (dot (dot (dot pac--HSTX_CTRL (csr))) (modify (lambda (w) (dot w (set_clkdiv 7)))))
       (dot (dot (dot pac--HSTX_CTRL (csr))) (modify (lambda (w) (dot w (set_clkphase 0)))))
       (dot (dot (dot pac--HSTX_CTRL (bit 0))) (modify (lambda (w) (dot w (set_sel_p 0)))))
       (dot (dot (dot pac--HSTX_CTRL (bit 0))) (modify (lambda (w) (dot w (set_sel_n 31)))))
       (dot (dot (dot pac--HSTX_CTRL (bit 0))) (modify (lambda (w) (dot w (set_inv false)))))
       (dot (dot (dot pac--HSTX_CTRL (bit 0))) (modify (lambda (w) (dot w (set_clk false)))))
       (dot (dot (dot pac--HSTX_CTRL (csr))) (modify (lambda (w) (dot w (set_en true))))))

     (defun hstx_dma_start (buf)
       (declare (type "&[u32; 256]" buf))
       (let ((ch (dot pac--DMA (ch 0))))
	 (dot (dot ch (read_addr)) (write_value (coerce (dot buf (as_ptr)) u32)))
	 (dot (dot ch (write_addr)) (write_value (coerce (dot (dot pac--HSTX_FIFO (fifo)) (as_ptr)) u32)))
	 (dot (dot ch (trans_count)) (modify (lambda (w) (dot w (set_mode pac--dma--vals--TransCountMode--NORMAL)))))
	 (dot (dot ch (trans_count)) (modify (lambda (w) (dot w (set_count 4294967295)))))
	 (dot (dot ch (ctrl_trig)) (modify (lambda (w) (dot w (set_en false)))))
	 (dot (dot ch (ctrl_trig)) (modify (lambda (w) (dot w (set_data_size pac--dma--vals--DataSize--SIZE_WORD)))))
	 (dot (dot ch (ctrl_trig)) (modify (lambda (w) (dot w (set_incr_read true)))))
	 (dot (dot ch (ctrl_trig)) (modify (lambda (w) (dot w (set_incr_write false)))))
	 (dot (dot ch (ctrl_trig)) (modify (lambda (w) (dot w (set_ring_size 10)))))
	 (dot (dot ch (ctrl_trig)) (modify (lambda (w) (dot w (set_ring_sel false)))))
	 (dot (dot ch (ctrl_trig)) (modify (lambda (w) (dot w (set_chain_to 0)))))
	 (dot (dot ch (ctrl_trig)) (modify (lambda (w) (dot w (set_treq_sel pac--dma--vals--TreqSel--HSTX)))))
	 (dot (dot ch (ctrl_trig)) (modify (lambda (w) (dot w (set_irq_quiet true)))))
	 (dot (dot ch (ctrl_trig)) (modify (lambda (w) (dot w (set_en true))))))))

     (defun hstx_rebuild (buf freq_hz amp_tenth phase_deg)
       (declare (type "&mut [u32; 256]" buf)
		(type u32 freq_hz)
		(type u16 amp_tenth phase_deg))
       (let ((cyc (/ (* freq_hz 8192) 15625000)))
	 (declare (type u32 cyc))
	 (setf cyc (if (< cyc 1) 1 (if (< 64 cyc) 64 cyc)))
	 (let ((poff (/ (* (coerce phase_deg u32) 64) 360)))
	   (declare (type u32 poff))
	   (dotimes (w 256)
	     (let ((word 0)
		   (bit (coerce 1 u32)))
	       (declare (type u32 word bit)
			(mutable word bit))
	       (dotimes (b 32)
		 (let ((pos (+ (* (coerce w u32) 32) (coerce b u32))))
		   (declare (type u32 pos))
		   (let ((sph (% (/ (* (* pos cyc) 64) 8192) 64))
			 (duty (/ (* (coerce (aref SIN_Q16 (coerce (% (+ sph poff) 64) usize)) u32) (coerce amp_tenth u32)) 1000))
			 (saw (* (% pos 128) 512)))
		     (declare (type u32 sph duty saw))
		     (when (< saw duty)
		       (|=| word bit)))
		   (<<= bit 1)))
	       (setf (aref buf w) word))))))

     "#[embassy_executor::task]"
     (defun-async hstx_task (buf)
       (declare (type "&'static mut [u32; 256]" buf)
		(mutable buf))
       (hstx_init)
       (let ((freq 30)
	     (amp 800))
	 (declare (type u32 freq)
		  (type u16 amp)
		  (mutable freq amp))
	 (hstx_rebuild "&mut *buf" freq amp 0)
	 (hstx_dma_start "&*buf")
	 (loop
	   (while-let ((Ok cmd) (dot HSTX_CH (try_receive))
	     (setf freq (dot (dot cmd freq_hz) (clamp 1 2000)))
	     (setf amp (dot (dot cmd amp_tenth_pct) (clamp 0 1000)))
	     (hstx_rebuild "&mut *buf" freq amp (dot cmd phase_deg))
	     (hstx_dma_start "&*buf")))
	   (await (Timer--after (Duration--from_millis 200))))))

     (defun-async send_status (tx seq)
       (declare (type "&mut embassy_rp::uart::BufferedUartTx" tx)
		(type u8 seq)
		(mutable tx))
       (let ((tg (await (dot TEMP_VAL (lock))))
	     (cg (await (dot CAP_VAL (lock)))))
	 (let ((msg (make-instance proto--StatusMsg :seq seq :temp_c10 (temp_raw_to_c10 (deref tg)) :cap (deref cg) :flags 0))
	       (wire (array-repeat 0 9))
	       (frame (array-repeat 0 68)))
	   (declare (type "[u8; 9]" wire)
		    (type "[u8; 68]" frame)
		    (mutable wire frame))
	   (proto--encode_status (ref msg) "&mut wire")
	   (if-let ((Some n) (proto--encode_frame (ref wire) "&mut frame"))
	     (do0 (let ((r (await (dot tx (write_all "&frame[..n]")))))
		    (when (dot r (is_err))
		      (return))))))))

     (defun-async send_block (tx ch m)
       (declare (type "&mut embassy_rp::uart::BufferedUartTx" tx)
		(type u8 ch)
		(type u16 m)
		(mutable tx))
       (let ((g (await (dot BLOCK_BUF (lock)))))
	 (let ((off 0))
	   (declare (type u16 off)
		    (mutable off))
	   (while (< off m)
	     (let ((k (if (< (- m off) 30) (- m off) 30)))
	       (declare (type u16 k))
	       (let ((pl (array-repeat 0 64))
		     (frame (array-repeat 0 68)))
		 (declare (type "[u8; 64]" pl)
			  (type "[u8; 68]" frame)
			  (mutable pl frame))
		 (setf (aref pl 0) proto--TAG_ADC_BLOCK)
		 (setf (aref pl 1) ch)
		 (proto--put_u16_le "&mut pl" 2 k)
		 (dotimes (j (coerce k usize))
		   (proto--put_u16_le "&mut pl" (+ 4 (* 2 j)) (aref g (coerce (+ (coerce off usize) j) usize))))
		 (let ((len (+ 4 (* 2 (coerce k usize))))))
		 (if-let ((Some n) (proto--encode_frame "&pl[..len]" "&mut frame"))
		   (do0 (let ((r (await (dot tx (write_all "&frame[..n]")))))
			  (when (dot r (is_err))
			    (return))))))
	       (setf off (+ off k)))))))

     "#[embassy_executor::task]"
     (defun-async uart_task (uart)
       (declare (type "embassy_rp::uart::BufferedUart" uart)
		(mutable uart))
       (let ((dec (proto--Decoder--new))
	     (one (array-repeat 0 1))
	     (seq 0)
	     (last (Instant--now))
	     (both (dot uart (split)))
	     (tx (dot both 0))
	     (rx (dot both 1)))
	 (declare (type "[u8; 1]" one)
		  (type u8 seq)
		  (mutable dec one seq last tx rx))
	 (loop
	   (let ((r (await (embassy_time--with_timeout (Duration--from_millis 100) (dot rx (read_exact "&mut one"))))))
	     (if-let ((Ok inner) r)
	       (when (dot inner (is_ok))
		 (if-let ((Some n) (dot dec (push (aref one 0))))
		   (do0 (let ((pl (array-repeat 0 64)))
			 (declare (type "[u8; 64]" pl)
				  (mutable pl))
			 (dotimes (i (coerce n usize))
			   (setf (aref pl i) (dot dec (payload_byte i))))
			 (let ((tag (aref pl 0)))
		     (if (and (== tag proto--TAG_SET_PWM) (== n 10))
			 (if-let ((Some cmd) (proto--decode_pwm_cmd "&pl[..10]"))
			   (await (dot PWM_CH (send cmd))))
			 (if (and (== tag proto--TAG_SET_HSTX) (== n 9))
			     (if-let ((Some cmd) (proto--decode_hstx_cmd "&pl[..9]"))
			       (await (dot HSTX_CH (send cmd))))
			     (if (and (== tag proto--TAG_SET_ADC) (== n 7))
				 (if-let ((Some cmd) (proto--decode_adc_cmd "&pl[..7]"))
				   (await (dot ADC_CH (send cmd))))
				 (if (and (== tag proto--TAG_CAP_SELECT) (== n 2))
				     (await (dot CAP_CH (send (aref pl 1))))
				     (if (and (== tag proto--TAG_READ_BLOCK) (== n 4))
					 (await (dot READ_CH (send (paren (aref pl 1) (proto--get_u16_le "&pl[..4]" 2)))))
					 (do0 (defmt--warn! (string "uart: unknown tag={} len={}") tag n)))))))))))))
	   (when (< 500 (coerce (dot (dot last (elapsed)) (as_millis)) u64))
	     (await (send_status "&mut tx" seq))
	     (setf seq (dot seq (wrapping_add 1)))
	     (setf last (Instant--now)))
	   (while-let ((Ok ready) (dot BLOCK_READY (try_receive)))
	     (await (send_block "&mut tx" (dot ready 0) (dot ready 1)))))))

     "#[embassy_executor::main]"
     (defun-async main (spawner)
       (declare (type "embassy_executor::Spawner" spawner))
      (let ((p (embassy_rp--init (Default--default)))
	    (uart (Uart--new_blocking (dot p UART0) (dot p PIN_0) (dot p PIN_1) (UartConfig--default)))
	    (txb (dot UART_TX_BUF (init (array-repeat 0 256))))
	    (rxb (dot UART_RX_BUF (init (array-repeat 0 256))))
	    (buart (dot uart (into_buffered Irqs txb rxb)))
	    (adc (Adc--new (dot p ADC) Irqs (make-instance AdcConfig)))
	    (pwm0 (Pwm--new_output_a (dot p PWM_SLICE1) (dot p PIN_2) (pwm_carrier)))
	    (pwm1 (Pwm--new_output_a (dot p PWM_SLICE2) (dot p PIN_4) (pwm_carrier)))
	    (pwm2 (Pwm--new_output_a (dot p PWM_SLICE3) (dot p PIN_6) (pwm_carrier)))
	    (pwm3 (Pwm--new_output_a (dot p PWM_SLICE4) (dot p PIN_8) (pwm_carrier)))
	    (pio (Pio--new (dot p PIO0) Irqs))
	    (cap_pin (dot (dot pio common) (make_pio_pin (dot p PIN_22))))
	    (prog (dot (dot pio common) (load_program CAP_PROG)))
	    (cfg (PioConfig--default))
	    (hbuf (dot HSTX_BUF_CELL (init (array-repeat 0 256))))
	    (led (Output--new (dot p PIN_25) Level--Low)))
	(declare (mutable cfg led))
       (dot (spawner.spawn (adc_task adc (dot p PIN_26) (dot p PIN_27) (dot p PIN_28) (dot p ADC_TEMP_SENSOR))) (unwrap))
       (dot (spawner.spawn (pwm_task pwm0 pwm1 pwm2 pwm3)) (unwrap))
       (dot (spawner.spawn (cap_task (dot (dot pio sm0) rx) (dot p PIN_20) (dot p PIN_21) (dot p PIN_23))) (unwrap))
       (dot (spawner.spawn (hstx_task hbuf)) (unwrap))
       (dot (spawner.spawn (uart_task buart)) (unwrap))
       (await (dot PWM_CH (send (make-instance proto--PwmCmd :ch 0 :freq_hz 5 :amp_tenth_pct 800 :phase_deg 0))))
       (await (dot PWM_CH (send (make-instance proto--PwmCmd :ch 1 :freq_hz 5 :amp_tenth_pct 800 :phase_deg 90))))
       (await (dot PWM_CH (send (make-instance proto--PwmCmd :ch 2 :freq_hz 5 :amp_tenth_pct 800 :phase_deg 180))))
       (await (dot PWM_CH (send (make-instance proto--PwmCmd :ch 3 :freq_hz 5 :amp_tenth_pct 800 :phase_deg 270))))
       (await (dot HSTX_CH (send (make-instance proto--HstxCmd :freq_hz 30 :amp_tenth_pct 800 :phase_deg 0))))
       (await (dot ADC_CH (send (make-instance proto--AdcCmd :rate_hz 1000 :phase_deg 0))))
       (loop
	 (dot led (set_high))
	 (await (Timer--after (Duration--from_millis 100)))
	 (dot led (set_low))
	 (await (Timer--after (Duration--from_millis 900)))))))
))
