(eval-when (:compile-toplevel :execute :load-toplevel)
  (ql:quickload "cl-rust-generator"))

(in-package :cl-rust-generator)

;; gen20_host.lisp -- generates the Linux TUI control program (host_ctl).
;; Serial UART client + ratatui panels for PWM / HSTX / ADC / cap / live
;; values. `--port PATH --baud N`; `--demo` simulates a device so the TUI
;; can be exercised without hardware. Pure step helpers carry unit tests.

(let ((*omit-redundant-parens* t)
      (*rustfmt-arguments* (list "--edition" "2024")))
  (defparameter *host-dir* #P"examples/23_embassy_pico/host_ctl/")
  (defun host-path (name)
    (asdf:system-relative-pathname 'cl-rust-generator
				   (merge-pathnames name *host-dir*)))
  (defun host-write (rel content)
    (let ((fn (host-path rel)))
      (ensure-directories-exist fn)
      (with-open-file (s fn :direction :output
			    :if-exists :supersede
			    :if-does-not-exist :create)
	(write-sequence content s))
      fn))

  (host-write #P"Cargo.toml"
	      "[package]
name = \"pico-host-ctl\"
version = \"0.1.0\"
edition = \"2024\"
description = \"Linux TUI control program for the Pico 2 firmware (generated from gen20_host.lisp, do not edit by hand)\"
license = \"MIT OR Apache-2.0\"

[[bin]]
name = \"pico-host-ctl\"
path = \"src/main.rs\"

[dependencies]
pico-link-proto = { path = \"../proto\" }
ratatui = \"0.30\"
crossterm = \"0.29\"
serialport = \"4.10\"
")

  (write-source
   (host-path #P"src/main.rs")
   `(do0
     "use crossterm::event::{self, Event, KeyCode};"
     "use pico_link_proto as proto;"
     "use serialport::SerialPort;"
     "use ratatui::layout::{Constraint, Direction, Layout};"
     "use ratatui::text::Line;"
     "use ratatui::widgets::{Block, Paragraph};"
     "use std::io::{Read, Write};"
     "use std::time::{Duration, Instant};"
     "type FocusName = &'static str;"

     (space pub (defstruct0 App
       ((space pub focus) u8)
       ((space pub pwm_ch) u8)
       ((space pub freq) "[u32; 4]")
       ((space pub amp) "[u16; 4]")
       ((space pub phase) "[u16; 4]")
       ((space pub hstx_freq) u32)
       ((space pub hstx_amp) u16)
       ((space pub hstx_phase) u16)
       ((space pub adc_rate) u32)
       ((space pub adc_phase) u16)
       ((space pub cap_sel) u8)
       ((space pub blk_ch) u8)
       ((space pub temp_c10) i16)
       ((space pub cap) u32)
       ((space pub seq) u8)
       ((space pub block) "Vec<u16>")
       ((space pub quit) bool)))

     (space pub (defun app_new ()
       (declare (values App))
       (make-instance App
	 :focus 0 :pwm_ch 0
	 :freq (array-repeat 5 4)
	 :amp (array-repeat 800 4)
	 :phase (array-repeat 0 4)
	 :hstx_freq 30 :hstx_amp 800 :hstx_phase 0
	 :adc_rate 1000 :adc_phase 0
	 :cap_sel 3 :blk_ch 0
	 :temp_c10 0 :cap 0 :seq 0
	 :block (vec!) :quit false)))

     (space pub (defun step_freq (f up)
       (declare (type u32 f)
		(type bool up)
		(values u32))
       (if up
	   (dot (+ f 10) (clamp 1 2000))
	   (dot (dot f (saturating_sub 10)) (max 1)))))

     (space pub (defun step_rate (r up)
       (declare (type u32 r)
		(type bool up)
		(values u32))
       (if up
	   (dot (+ r 100) (clamp 1 20000))
	   (dot (dot r (saturating_sub 100)) (max 1)))))

     (space pub (defun step_amp (a up)
       (declare (type u16 a)
		(type bool up)
		(values u16))
       (if up
	   (dot (+ a 50) (clamp 0 1000))
	   (dot a (saturating_sub 50)))))

     (space pub (defun step_phase (p up)
       (declare (type u16 p)
		(type bool up)
		(values u16))
       (% (+ p (if up 15 345)) 360)))

     (space pub (defun focus_name (f)
       (declare (type u8 f)
		(values FocusName))
       (if (== f 0)
	   (string "PWM")
	   (if (== f 1)
	       (string "HSTX")
	       (string "ADC")))))

     "#[cfg(test)]"
     "mod tests {"
     "use super::*;"
     "#[test]"
     (defun step_freq_clamp ()
       (assert_eq! 2000 (step_freq 1995 true))
       (assert_eq! 60 (step_freq 50 true))
       (assert_eq! 1 (step_freq 5 false)))
     "#[test]"
     (defun step_rate_clamp ()
       (assert_eq! 20000 (step_rate 19950 true))
       (assert_eq! 1100 (step_rate 1000 true))
       (assert_eq! 1 (step_rate 50 false)))
     "#[test]"
     (defun step_amp_clamp ()
       (assert_eq! 1000 (step_amp 980 true))
       (assert_eq! 750 (step_amp 800 false))
       (assert_eq! 0 (step_amp 20 false)))
     "#[test]"
     (defun step_phase_wrap ()
       (assert_eq! 5 (step_phase 350 true))
       (assert_eq! 345 (step_phase 0 false))
       (assert_eq! 10 (step_phase 355 true)))
     "#[test]"
     (defun focus_names ()
       (assert_eq! (string "PWM") (focus_name 0))
       (assert_eq! (string "HSTX") (focus_name 1))
       (assert_eq! (string "ADC") (focus_name 2)))
     "}"

     (space pub (defun send_pwm (port ch freq amp phase)
       (declare (type "&mut Option<Box<dyn SerialPort>>" port)
		(type u8 ch)
		(type u32 freq)
		(type u16 amp phase))
       (if-let ((Some p) port)
	 (do0 (let ((cmd (make-instance proto--PwmCmd :ch ch :freq_hz freq :amp_tenth_pct amp :phase_deg phase))
		    (wire (array-repeat 0 10))
		    (frame (array-repeat 0 68)))
		(declare (type "[u8; 10]" wire)
			 (type "[u8; 68]" frame)
			 (mutable wire frame))
		(proto--encode_pwm_cmd (ref cmd) "&mut wire")
		(if-let ((Some n) (proto--encode_frame (ref wire) "&mut frame"))
		  (let ((_ (dot p (write_all "&frame[..n]")))))))))))

     (space pub (defun send_hstx (port freq amp phase)
       (declare (type "&mut Option<Box<dyn SerialPort>>" port)
		(type u32 freq)
		(type u16 amp phase))
       (if-let ((Some p) port)
	 (do0 (let ((cmd (make-instance proto--HstxCmd :freq_hz freq :amp_tenth_pct amp :phase_deg phase))
		    (wire (array-repeat 0 9))
		    (frame (array-repeat 0 68)))
		(declare (type "[u8; 9]" wire)
			 (type "[u8; 68]" frame)
			 (mutable wire frame))
		(proto--encode_hstx_cmd (ref cmd) "&mut wire")
		(if-let ((Some n) (proto--encode_frame (ref wire) "&mut frame"))
		  (let ((_ (dot p (write_all "&frame[..n]")))))))))))

     (space pub (defun send_adc (port rate phase)
       (declare (type "&mut Option<Box<dyn SerialPort>>" port)
		(type u32 rate)
		(type u16 phase))
       (if-let ((Some p) port)
	 (do0 (let ((cmd (make-instance proto--AdcCmd :rate_hz rate :phase_deg phase))
		    (wire (array-repeat 0 7))
		    (frame (array-repeat 0 68)))
		(declare (type "[u8; 7]" wire)
			 (type "[u8; 68]" frame)
			 (mutable wire frame))
		(proto--encode_adc_cmd (ref cmd) "&mut wire")
		(if-let ((Some n) (proto--encode_frame (ref wire) "&mut frame"))
		  (let ((_ (dot p (write_all "&frame[..n]")))))))))))

     (space pub (defun send_cap (port sel)
       (declare (type "&mut Option<Box<dyn SerialPort>>" port)
		(type u8 sel))
       (if-let ((Some p) port)
	 (do0 (let ((pl (array-repeat 0 2))
		    (frame (array-repeat 0 68)))
		(declare (type "[u8; 2]" pl)
			 (type "[u8; 68]" frame)
			 (mutable pl frame))
		(setf (aref pl 0) proto--TAG_CAP_SELECT)
		(setf (aref pl 1) sel)
		(if-let ((Some n) (proto--encode_frame (ref pl) "&mut frame"))
		  (let ((_ (dot p (write_all "&frame[..n]")))))))))))

     (space pub (defun send_readblock (port ch want)
       (declare (type "&mut Option<Box<dyn SerialPort>>" port)
		(type u8 ch)
		(type u16 want))
       (if-let ((Some p) port)
	 (do0 (let ((pl (array-repeat 0 4))
		    (frame (array-repeat 0 68)))
		(declare (type "[u8; 4]" pl)
			 (type "[u8; 68]" frame)
			 (mutable pl frame))
		(setf (aref pl 0) proto--TAG_READ_BLOCK)
		(setf (aref pl 1) ch)
		(proto--put_u16_le "&mut pl" 2 want)
		(if-let ((Some n) (proto--encode_frame (ref pl) "&mut frame"))
		  (let ((_ (dot p (write_all "&frame[..n]")))))))))))

     (space pub (defun send_focused (port app)
       (declare (type "&mut Option<Box<dyn SerialPort>>" port)
		(type "&App" app))
       (if (== (dot app focus) 0)
	   (send_pwm port (dot app pwm_ch)
		     (aref (dot app freq) (coerce (dot app pwm_ch) usize))
		     (aref (dot app amp) (coerce (dot app pwm_ch) usize))
		     (aref (dot app phase) (coerce (dot app pwm_ch) usize)))
	   (if (== (dot app focus) 1)
	       (send_hstx port (dot app hstx_freq) (dot app hstx_amp) (dot app hstx_phase))
	       (send_adc port (dot app adc_rate) (dot app adc_phase))))))

     (space pub (defun handle_payload (app pl n)
       (declare (type "&mut App" app)
		(type "&[u8]" pl)
		(type usize n))
       (let ((tag (aref pl 0)))
	 (if (and (== tag proto--TAG_STATUS) (== n 9))
	     (if-let ((Some st) (proto--decode_status "&pl[..9]"))
	       (do0 (setf (dot app temp_c10) (dot st temp_c10))
		    (setf (dot app cap) (dot st cap))
		    (setf (dot app seq) (dot st seq))))
	     (if (and (== tag proto--TAG_ADC_BLOCK) (<= 4 n))
		 (do0 (setf (dot app blk_ch) (aref pl 1))
		      (let ((k (proto--get_u16_le pl 2))
			    (v (vec!)))
			(declare (type "Vec<u16>" v)
				 (mutable v))
			(dotimes (i (coerce k usize))
			  (dot v (push (proto--block_sample pl i))))
			(setf (dot app block) v))))))))

     (space pub (defun pump_serial (port dec app)
       (declare (type "&mut Option<Box<dyn SerialPort>>" port)
		(type "&mut proto::Decoder" dec)
		(type "&mut App" app))
       (if-let ((Some p) port)
	 (do0 (let ((buf (array-repeat 0 256)))
		(declare (type "[u8; 256]" buf)
			 (mutable buf))
		(case (dot p (read "&mut buf"))
		  ((Ok n) (dotimes (i n)
			    (if-let ((Some m) (dot dec (push (aref buf i))))
			      (do0 (let ((pl (array-repeat 0 64)))
				     (declare (type "[u8; 64]" pl)
					      (mutable pl))
				     (dotimes (j m)
				       (setf (aref pl j) (dot dec (payload_byte j))))
				     (handle_payload app "&pl" m))))))
		  ((Err _) nil)))))))

     (space pub (defun adjust_freq_focused (app up)
       (declare (type "&mut App" app)
		(type bool up))
       (if (== (dot app focus) 0)
	   (let ((ch (coerce (dot app pwm_ch) usize)))
	     (declare (type usize ch))
	     (setf (aref (dot app freq) ch)
		   (step_freq (aref (dot app freq) ch) up)))
	   (if (== (dot app focus) 1)
	       (setf (dot app hstx_freq) (step_freq (dot app hstx_freq) up))
	       (setf (dot app adc_rate) (step_rate (dot app adc_rate) up))))))

     (space pub (defun adjust_amp_focused (app up)
       (declare (type "&mut App" app)
		(type bool up))
       (if (== (dot app focus) 0)
	   (let ((ch (coerce (dot app pwm_ch) usize)))
	     (declare (type usize ch))
	     (setf (aref (dot app amp) ch)
		   (step_amp (aref (dot app amp) ch) up)))
	   (if (== (dot app focus) 1)
	       (setf (dot app hstx_amp) (step_amp (dot app hstx_amp) up))
	       (setf (dot app adc_phase) (step_phase (dot app adc_phase) up))))))

     (space pub (defun adjust_phase_focused (app up)
       (declare (type "&mut App" app)
		(type bool up))
       (if (== (dot app focus) 0)
	   (let ((ch (coerce (dot app pwm_ch) usize)))
	     (declare (type usize ch))
	     (setf (aref (dot app phase) ch)
		   (step_phase (aref (dot app phase) ch) up)))
	   (if (== (dot app focus) 1)
	       (setf (dot app hstx_phase) (step_phase (dot app hstx_phase) up))
	       (setf (dot app adc_phase) (step_phase (dot app adc_phase) up))))))

     (space pub (defun pwm_lines (app)
       (declare (type "&App" app)
                (values "Vec<Line<'_>>"))
       (let ((lines (vec! (Line--from (string "ch  f/Hz  amp  phase")))))
         (declare (type "Vec<Line>" lines)
                  (mutable lines))
         (dotimes (ch 4)
           (dot lines (push (Line--from (format! (string "ch{} {:>5} {:>4} {:>3}{}")
                                                ch
                                                (aref (dot app freq) ch)
                                                (aref (dot app amp) ch)
                                                (aref (dot app phase) ch)
                                                (if (== ch (coerce (dot app pwm_ch) usize))
                                                    (string " <")
                                                    (string "")))))))
         lines)))

     (space pub (defun draw (terminal app)
       (declare (type "&mut ratatui::DefaultTerminal" terminal)
                (type "&App" app)
                (values "std::io::Result<()>"))
       (? (dot terminal (draw (lambda (frame)
         (let ((layout (dot (dot (Layout--default) (direction Direction--Vertical))
                            (constraints (list (Constraint--Length 8) (Constraint--Length 10) (Constraint--Min 8))))))
        (dot frame (render_widget (Paragraph--block (Paragraph--new (pwm_lines app))
                                                             (dot (Block--bordered) (title (string "PWM sine"))))
                                           (aref (dot layout (split (dot frame (area)))) 0)))
        (dot frame (render_widget (Paragraph--block (Paragraph--new (vec! (Line--from (format! (string "HSTX f={}Hz a={} p={}")
                                         (dot app hstx_freq) (dot app hstx_amp) (dot app hstx_phase)))
               (Line--from (format! (string "ADC rate={}Hz phase={}")
                                    (dot app adc_rate) (dot app adc_phase)))
               (Line--from (format! (string "cap={} blk={} (c/v)")
                                    (dot app cap_sel) (dot app blk_ch)))))
                                                             (dot (Block--bordered) (title (string "HSTX/ADC"))))
                                           (aref (dot layout (split (dot frame (area)))) 1)))
        (dot frame (render_widget (Paragraph--block (Paragraph--new (vec! (Line--from (format! (string "temp={}x0.1C cap={} seq={} focus={}")
                                         (dot app temp_c10) (dot app cap) (dot app seq)
                                         (focus_name (dot app focus))))
               (Line--from (format! (string "block n={} first={}")
                                    (dot (dot app block) (len))
                                    (if (== (dot (dot app block) (len)) 0)
                                        0
                                        (aref (dot app block) 0))))
               (Line--from (string "q quit|Tab focus|1-4 ch|-/= f|[/] a|;/' p"))
               (Line--from (string "s send|c cap|v blkch|b read"))))
                                                             (dot (Block--bordered) (title (string "Live"))))
                                           (aref (dot layout (split (dot frame (area)))) 2))))))))
       (Ok (tuple))))

     (space pub (defun run (terminal)
       (declare (type "&mut ratatui::DefaultTerminal" terminal)
		(values "std::io::Result<()>"))
       (let ((args (dot (std--env--args) (collect)))
	     (port_name (dot (string "/dev/ttyUSB0") (to_string)))
	     (baud 115200)
	     (demo false)
	     (i 1))
	 (declare (type "Vec<String>" args)
		  (type String port_name)
		  (type u32 baud)
		  (type bool demo)
		  (type usize i)
		  (mutable port_name baud demo i))
	 (while (< i (dot args (len)))
	   (if (== (aref args i) (string "--port"))
	       (do0 (incf i)
		    (setf port_name (dot (aref args i) (clone))))
	       (if (== (aref args i) (string "--baud"))
		   (do0 (incf i)
			(setf baud (dot (dot (aref args i) (parse)) (unwrap_or 115200))))
		   (when (== (aref args i) (string "--demo"))
		     (setf demo true))))
	   (incf i))
	 (let ((port None))
	   (declare (type "Option<Box<dyn SerialPort>>" port)
		    (mutable port))
	   (if (not demo)
	       (case (dot (dot (serialport--new port_name baud)
			       (timeout (Duration--from_millis 50)))
			  (open))
		 ((Ok p) (setf port (Some p)))
		 ((Err e) (return (Err (std--io--Error--new std--io--ErrorKind--Other
							(dot e (to_string))))))))
	   (let ((app (app_new))
		 (dec (proto--Decoder--new))
		 (last (Instant--now)))
	     (declare (mutable app dec last))
	     (while (not (dot app quit))
	       (when (? (event--poll (Duration--from_millis 50)))
		 (case (? (event--read))
		   ((Event--Key key)
		    (do0
		      (when (== (dot key code) (KeyCode--Char (char q)))
			(setf (dot app quit) true))
		      (when (== (dot key code) KeyCode--Tab)
			(setf (dot app focus) (% (+ (dot app focus) 1) 3)))
		      (when (== (dot key code) (KeyCode--Char (char 1)))
			(setf (dot app pwm_ch) 0))
		      (when (== (dot key code) (KeyCode--Char (char 2)))
			(setf (dot app pwm_ch) 1))
		      (when (== (dot key code) (KeyCode--Char (char 3)))
			(setf (dot app pwm_ch) 2))
		      (when (== (dot key code) (KeyCode--Char (char 4)))
			(setf (dot app pwm_ch) 3))
		      (when (== (dot key code) (KeyCode--Char (char -)))
			(adjust_freq_focused "&mut app" false))
		      (when (== (dot key code) (KeyCode--Char (char =)))
			(adjust_freq_focused "&mut app" true))
		      (when (== (dot key code) (KeyCode--Char (char [)))
			(adjust_amp_focused "&mut app" false))
		      (when (== (dot key code) (KeyCode--Char (char ])))
			(adjust_amp_focused "&mut app" true))
		      (when (== (dot key code) (KeyCode--Char (char \;)))
			(adjust_phase_focused "&mut app" false))
		      (when (== (dot key code) (KeyCode--Char (char "\\'")))
			(adjust_phase_focused "&mut app" true))
		      (when (== (dot key code) (KeyCode--Char (char s)))
			(send_focused "&mut port" "&app"))
		      (when (== (dot key code) (KeyCode--Char (char c)))
			(do0 (setf (dot app cap_sel) (% (+ (dot app cap_sel) 1) 4))
			     (send_cap "&mut port" (dot app cap_sel))))
		      (when (== (dot key code) (KeyCode--Char (char v)))
			(setf (dot app blk_ch) (% (+ (dot app blk_ch) 1) 3)))
		      (when (== (dot key code) (KeyCode--Char (char b)))
			(send_readblock "&mut port" (dot app blk_ch) 128))))
		   (_ nil)))
	       (pump_serial "&mut port" "&mut dec" "&mut app")
	       (when demo
		 (when (< 500 (coerce (dot (dot last (elapsed)) (as_millis)) u64))
		   (do0 (setf (dot app temp_c10) (+ (dot app temp_c10) 1))
			(setf (dot app cap) (+ (dot app cap) 37))
			(setf (dot app seq) (dot (dot app seq) (wrapping_add 1)))
			(setf last (Instant--now)))))
	       (? (draw terminal "&app")))
	     (Ok (tuple)))))))

     (defun main ()
       (let ((terminal (ratatui--init)))
	 (declare (mutable terminal))
	 (dot (run "&mut terminal") (unwrap))
	 (ratatui--restore))))

))
