[package]
name = "lbw-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
lbw-common = { path = "../common" }
ort = { version = "2.0.0-rc.13", default-features = false, features = ["download-binaries", "copy-dylibs", "tls-native", "std"] }
rav1e = { version = "0.8.1", default-features = false, features = ["threading", "asm"] }
x11rb = { version = "0.14.0", features = ["xtest"] }

[dev-dependencies]
lbw-client = { path = "../client" }
lbw-throttle = { path = "../throttle" }
