// This file is @generated by prost-build.
/// --- CLIENT -> SERVER ---
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientEvent {
    #[prost(oneof = "client_event::Event", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub event: ::core::option::Option<client_event::Event>,
}
/// Nested message and enum types in `ClientEvent`.
pub mod client_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        Navigate(super::NavigateRequest),
        #[prost(message, tag = "2")]
        Mouse(super::MouseInput),
        #[prost(message, tag = "3")]
        Keyboard(super::KeyboardInput),
        #[prost(message, tag = "4")]
        Scroll(super::ScrollInput),
        #[prost(message, tag = "5")]
        Resize(super::ViewportResize),
        #[prost(message, tag = "6")]
        Config(super::StreamConfig),
        #[prost(message, tag = "7")]
        Search(super::SearchRequest),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NavigateRequest {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MouseInput {
    #[prost(int32, tag = "1")]
    pub x: i32,
    #[prost(int32, tag = "2")]
    pub y: i32,
    #[prost(uint32, tag = "3")]
    pub button: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyboardInput {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ScrollInput {
    #[prost(int32, tag = "1")]
    pub delta_y: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ViewportResize {
    #[prost(uint32, tag = "1")]
    pub width: u32,
    #[prost(uint32, tag = "2")]
    pub height: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StreamConfig {
    #[prost(bool, tag = "1")]
    pub enable_video: bool,
    #[prost(bool, tag = "2")]
    pub enable_spatial_links: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
}
/// --- SERVER -> CLIENT ---
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerUpdate {
    #[prost(oneof = "server_update::Update", tags = "1, 2, 3, 4")]
    pub update: ::core::option::Option<server_update::Update>,
}
/// Nested message and enum types in `ServerUpdate`.
pub mod server_update {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Update {
        #[prost(message, tag = "1")]
        Frame(super::VideoFrame),
        #[prost(message, tag = "2")]
        SpatialData(super::SpatialMetadata),
        #[prost(message, tag = "3")]
        SearchResults(super::SearchResults),
        #[prost(message, tag = "4")]
        Status(super::SystemStatus),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VideoFrame {
    /// rav1e Output
    #[prost(bytes = "vec", tag = "1")]
    pub av1_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "2")]
    pub is_keyframe: bool,
    /// X-Position des aktuellen Bildausschnitts im Gesamtdokument
    #[prost(int32, tag = "3")]
    pub viewport_x: i32,
    /// Y-Position des aktuellen Bildausschnitts im Gesamtdokument
    #[prost(int32, tag = "4")]
    pub viewport_y: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpatialMetadata {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub document_width: u32,
    #[prost(uint32, tag = "3")]
    pub document_height: u32,
    #[prost(message, repeated, tag = "4")]
    pub links: ::prost::alloc::vec::Vec<LinkBox>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkBox {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub label: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub x: i32,
    #[prost(int32, tag = "5")]
    pub y: i32,
    #[prost(int32, tag = "6")]
    pub width: i32,
    #[prost(int32, tag = "7")]
    pub height: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchResults {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub matches: ::prost::alloc::vec::Vec<SearchMatch>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchMatch {
    /// Position im Dokument für "Jump to"
    #[prost(int32, tag = "1")]
    pub absolute_y: i32,
    /// Z.B. "...der\[Suchbegriff\] ist hier..."
    #[prost(string, tag = "2")]
    pub context_snippet: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemStatus {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod remote_browser_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct RemoteBrowserClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RemoteBrowserClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RemoteBrowserClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RemoteBrowserClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RemoteBrowserClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn stream_session(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::ClientEvent>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ServerUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/graphical_proxy.RemoteBrowser/StreamSession",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("graphical_proxy.RemoteBrowser", "StreamSession"),
                );
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod remote_browser_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RemoteBrowserServer.
    #[async_trait]
    pub trait RemoteBrowser: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the StreamSession method.
        type StreamSessionStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ServerUpdate, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn stream_session(
            &self,
            request: tonic::Request<tonic::Streaming<super::ClientEvent>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamSessionStream>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct RemoteBrowserServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> RemoteBrowserServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for RemoteBrowserServer<T>
    where
        T: RemoteBrowser,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/graphical_proxy.RemoteBrowser/StreamSession" => {
                    #[allow(non_camel_case_types)]
                    struct StreamSessionSvc<T: RemoteBrowser>(pub Arc<T>);
                    impl<
                        T: RemoteBrowser,
                    > tonic::server::StreamingService<super::ClientEvent>
                    for StreamSessionSvc<T> {
                        type Response = super::ServerUpdate;
                        type ResponseStream = T::StreamSessionStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::ClientEvent>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RemoteBrowser>::stream_session(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamSessionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for RemoteBrowserServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "graphical_proxy.RemoteBrowser";
    impl<T> tonic::server::NamedService for RemoteBrowserServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
