[package]
name = "code"
version = "0.1.0"
authors = ["Martin Kielhorn <kielhorn.martin@gmail.com>"]
edition = "2018"
[dependencies]
vulkano = "0.13"
vulkano-win = "*"
winit = "*"
chrono = "*"
vulkano-shaders= "0.13"
image = "*"
