[package]
name = "code"
version = "0.1.0"
authors = ["Martin Kielhorn <kielhorn.martin@gmail.com>"]
edition = "2018"
[dependencies]
vulkano = "0.13"
vulkano-win = "0.13"
winit = "0.22" #0.19
chrono = "*"
vulkano-shaders= "0.13"
image = "*"
