// Rust + C++ ImGui interop demo.
// Window and rendering live here in C++. The state struct and the
// per-frame logic live in Rust (rust_logic/src/lib.rs, generated by
// ../gen.lisp). Both sides must agree on AppState layout; the
// static_assert below guards the Rust #[repr(C)] side.
#include <cstdint>
#include <cstdio>

#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"
#include <GLFW/glfw3.h>

// Mirror of the Rust AppState (#[repr(C)], edition 2024).
struct AppState {
    int32_t click_count;
    float slider_value;
    bool checkbox_status;
};

// 4 + 4 + 1 + 3 padding on Linux/x86-64. Fail here, not silently.
static_assert(sizeof(AppState) == 12,
              "AppState layout drifted from Rust #[repr(C)] struct");

extern "C" {
AppState init_app_state();
void process_logic(AppState* state);
}

int main() {
    if (!glfwInit()) {
        return -1;
    }
    GLFWwindow* window =
        glfwCreateWindow(800, 600, "Rust + C++ ImGui Interop", nullptr, nullptr);
    if (!window) {
        glfwTerminate();
        return -1;
    }
    glfwMakeContextCurrent(window);
    glfwSwapInterval(1);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL3_Init("#version 130");

    AppState state = init_app_state();

    while (!glfwWindowShouldClose(window)) {
        glfwPollEvents();

        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();

        ImGui::Begin("Rust Logic Controller");
        ImGui::Text("This UI runs in C++, but the state lives in Rust!");

        if (ImGui::Button("Increment Click Counter")) {
            state.click_count++;
        }
        ImGui::Text("Counter value: %d", state.click_count);

        ImGui::SliderFloat("Speed Factor", &state.slider_value, 0.0f, 1.0f);
        ImGui::Checkbox("Auto-advance Slider via Rust",
                        &state.checkbox_status);
        ImGui::End();

        process_logic(&state);

        int display_w = 0;
        int display_h = 0;
        glfwGetFramebufferSize(window, &display_w, &display_h);
        glViewport(0, 0, display_w, display_h);
        glClearColor(0.45f, 0.55f, 0.60f, 1.00f);
        glClear(GL_COLOR_BUFFER_BIT);

        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

        glfwSwapBuffers(window);
    }

    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();
    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
