[package]
name = "sar_tdbp"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
# Gleiche Revision wie das verifizierte my_first_kernel-Template.
cuda-device = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "a0cc6cc0bc18722ec5cdfbea136c118a7c051977" }
cuda-host = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "a0cc6cc0bc18722ec5cdfbea136c118a7c051977" }
cuda-core = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "a0cc6cc0bc18722ec5cdfbea136c118a7c051977" }
macroquad = "0.4"
image = { version = "0.25", default-features = false, features = ["png"] }
